
title: "Suzanne Himmelberger — Réflexologue"
description: Réflexologie, région de Genève, Suisse
locale: fr

# url: "http://suzanne-himmelberger.ch"
url: "http://reflexohub.github.io/"
baseurl: "site-web-v1-test"

markdown: kramdown
kramdown:
  input: GFM

exclude: [ "CNAME", "README.md" ]

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

